### ISSUE TITLE
Code Review 1

### ISSUE THREAD

**Issue by Stefan-Bilokrynytskyi** [YanPetrov7/ConversoChat#16]
1. Carry out magic numbers to the variables: for example:
 `const errorStatus = 404;` 
[userController.js](https://github.com/YanPetrov7/ConversoChat/blob/main/src/js/userController.js#L45-L101)
2. Make code more laconic: 
`if(!notificationSound.muted)` 
instead of:
`if (notificationSound.muted === false)`
[home.js](https://github.com/YanPetrov7/ConversoChat/blob/7d84422fd1179166026af857f6e21ec602a28764/public/scripts/home.js#LL53C5-L53C5)
3. Use method string.includes():
`if(username.includes(filter))`
instead of 
`if (username.indexOf(filter) === -1)`
[home.js](https://github.com/YanPetrov7/ConversoChat/blob/7d84422fd1179166026af857f6e21ec602a28764/public/scripts/home.js#L185)
4. Make code more laconic: 
`'contacts' in data`
instead of: 
`data.hasOwnProperty('contacts')`
[home.js](https://github.com/YanPetrov7/ConversoChat/blob/7d84422fd1179166026af857f6e21ec602a28764/public/scripts/home.js#LL46C1-L46C1)
5. Add more ***error handlings*** for [home.js](https://github.com/YanPetrov7/ConversoChat/blob/7d84422fd1179166026af857f6e21ec602a28764/public/scripts/home.js)
6. Make data passwords inaccessable for the public
`password: "test1234"`
[config.json](https://github.com/YanPetrov7/ConversoChat/blob/7d84422fd1179166026af857f6e21ec602a28764/config/config.json#LL1C2-L1C2)
[docker-compose.yml](https://github.com/YanPetrov7/ConversoChat/blob/7d84422fd1179166026af857f6e21ec602a28764/docker-compose.yml#LL16C1-L16C3)
[docker-compose.yml](https://github.com/YanPetrov7/ConversoChat/blob/7d84422fd1179166026af857f6e21ec602a28764/docker-compose.yml#LL33C7-L33C7)

**Comment by YanPetrov7** [comment]
1) Refactor userController.js & home.js: https://github.com/YanPetrov7/ConversoChat/commit/1e3347128093d5dc21e393319178504c6650ce47
2) Make data passwords inaccessable for the public: https://github.com/YanPetrov7/ConversoChat/commit/d435806b232992ca656cf3729ada17643fd8541a & https://github.com/YanPetrov7/ConversoChat/commit/4a63485bc76c4b7f026ca67c95ba56cfd7eebe1e
