### ISSUE TITLE
Code Review 2

### ISSUE THREAD

**Issue by DanilYaremenko** [YanPetrov7/ConversoChat#29]
1) Discovered a bug where the logged in user can enter the null user by entering /home. 
2) Discovered a bug where the logged in user can enter the other user by changing url args. 
3) Write tests for this cases

**Comment by YanPetrov7** [comment]
1 & 2: Fix bugs: https://github.com/YanPetrov7/ConversoChat/commit/a11c521c1dcd41e37ebc4dc81647d880f14095e0
3: New tests: https://github.com/YanPetrov7/ConversoChat/commit/fd26c6ce005add6a6e9574a3c1831b229b7c47dc
